#!/usr/bin/env bash
# check-srs.sh — verify every requirement in SRS.md is traced to an artifact that exists.
# Confirms the traceability map is real (no dangling evidence links). Writes srs-results.txt.
#
# Usage: ./check-srs.sh    (run from PhysLean/process/)

set -u
here="$(cd "$(dirname "$0")" && pwd)"
S="$here/../submitted/Proof-Joint-convexity-of-the-Umegaki-quantum-relative-entropy"
out="$here/srs-results.txt"

# requirement | artifact path (relative to S, or repo-relative with @) | met|partial
rows=(
  "FR-SUB-001|evidence/checks.md|met"
  "FR-SUB-001|proof/qrelent-joint-convexity.patch|met"
  "FR-SUB-002|evidence/checks.md|met"
  "FR-SUB-003|verify.sh|met"
  "FR-SUB-004|paper/joint-convexity-proof.qmd|met"
  "FR-SUB-004|paper/joint-convexity-proof.pdf|met"
  "FR-SUB-005|test/fidelity-check.sh|met"
  "FR-SUB-005|test/fidelity-results.txt|met"
  "FR-SUB-006|test/literature-correspondence.md|met"
  "FR-SUB-006|test/source-comparison.md|met"
  "FR-SUB-006|test/results.txt|met"
  "FR-SUB-006|docs/literature.qmd|met"
  "FR-SUB-007|README.md|met"
  "FR-SUB-008|evidence/build-environment.md|partial"
  "FR-SUB-009|PR-BODY.md|met"
  "FR-SUB-010|PR-BODY.md|met"
)

pass=0; partial=0; missing=0
{
  echo "SRS check — requirement -> evidence artifact presence"
  echo "Generated by check-srs.sh"
  echo
  printf "%-13s %-8s %-6s %s\n" "requirement" "status" "file?" "artifact"
  printf '%.0s-' {1..78}; echo
  for r in "${rows[@]}"; do
    IFS='|' read -r req art status <<< "$r"
    if [ -e "$S/$art" ]; then
      exists="yes"
      [ "$status" = "partial" ] && partial=$((partial+1)) || pass=$((pass+1))
    else
      exists="NO"; missing=$((missing+1)); status="MISSING"
    fi
    printf "%-13s %-8s %-6s %s\n" "$req" "$status" "$exists" "$art"
  done
  echo
  echo "artifacts present: $((pass+partial))    of which partial: $partial    missing: $missing"
  if [ "$missing" -eq 0 ]; then
    echo "RESULT: PASS — every traced evidence artifact is present ($partial marked partial, none silently passed)."
  else
    echo "RESULT: FAIL — $missing traced artifact(s) missing."
  fi
} | tee "$out"

[ "$missing" -eq 0 ]
