#!/usr/bin/env bash
# compare-sources.sh — the machine-verifiable rows of source-comparison.md.
# Confirms the load-bearing statements are consistent across the three documents that
# should agree: the generated paper, the extracted Lean proof, and the physics brief.
# A mismatch would mean the paper claims something the Lean/brief do not state the same way.
#
# Usage: ./compare-sources.sh   (run from test/).  Writes results.txt.

set -u
here="$(cd "$(dirname "$0")" && pwd)"
paper="$here/../paper/joint-convexity-proof.qmd"
lean="$here/../proof/qRelativeEnt_joint_convexity.lean"
brief="$here/../docs/physics-brief.qmd"
out="$here/results.txt"

pass=0; fail=0
check() {  # description | file | pattern
  local desc="$1" file="$2" pat="$3" f
  f="$(basename "$file")"
  if grep -qE "$pat" "$file"; then
    printf "  PASS  %-46s [%s]\n" "$desc" "$f"; pass=$((pass+1))
  else
    printf "  FAIL  %-46s [%s]  /%s/\n" "$desc" "$f" "$pat"; fail=$((fail+1))
  fi
}

{
  echo "Source-consistency check (row 8 of source-comparison.md)"
  echo "Generated by compare-sources.sh"
  echo
  echo "A. Umegaki relative entropy — the trace formula Tr[rho (log rho - log sigma)]"
  check "paper states the Umegaki formula"  "$paper" 'log.?rho.*-.*log.?sigma|log\\\\rho - \\\\log\\\\sigma'
  check "brief states the Umegaki formula"  "$brief" 'log.?rho.*-.*log.?sigma|log\\\\rho - \\\\log\\\\sigma'

  echo
  echo "B. The joint-convexity inequality (mixture on the left, convex combo on the right)"
  check "paper states the theorem inequality" "$paper" 'le.*p.*D.*rho_1.*sigma_1|leq.*p'
  check "Lean carries the theorem name"       "$lean"  'qRelativeEnt_joint_convexity'
  check "brief states the inequality"         "$brief" 'le.*p.*D|leq'

  echo
  echo "C. Axioms — the correctness claim, stated identically"
  check "paper: propext/Classical.choice/Quot.sound" "$paper" 'propext.*Classical\.choice.*Quot\.sound|Classical\.choice'
  check "brief: same axiom list"                      "$brief" 'propext.*Classical\.choice.*Quot\.sound|Classical\.choice'

  echo
  echo "D. Proof route — the sandwiched alpha->1 limit, named consistently"
  check "paper names the alpha->1 / sandwiched route" "$paper" 'alpha.*1|sandwiched|Frank.Lieb'
  check "brief names the alpha->1 / sandwiched route" "$brief" 'alpha.*1|sandwiched|Frank.Lieb'

  echo
  echo "consistent statements: $pass    mismatches: $fail"
  if [ "$fail" -eq 0 ]; then
    echo "RESULT: PASS — the paper, the Lean proof, and the physics brief state the"
    echo "load-bearing facts (formula, theorem, axioms, route) consistently."
  else
    echo "RESULT: FAIL — $fail statement(s) not consistent across the documents."
  fi
} | tee "$out"

[ "$fail" -eq 0 ]
