#!/usr/bin/env bash
# fidelity-check.sh — confirm the conventional-maths paper tracks the Lean proof.
#
# For each Lean identifier the paper names as a load-bearing proof step, check it is
# present in the extracted proof section (for the NEW declarations) or is called by it
# (for the PRE-EXISTING inputs the proof consumes). Reports both directions and exits
# non-zero if any load-bearing correspondence is missing.
#
# Usage:  ./fidelity-check.sh            (run from the test/ directory)
# Output: prints a table; also writes fidelity-results.txt

set -u
here="$(cd "$(dirname "$0")" && pwd)"
paper="$here/../paper/joint-convexity-proof.qmd"
proof="$here/../proof/qRelativeEnt_joint_convexity.lean"
out="$here/fidelity-results.txt"

# Load-bearing Lean identifiers, and whether they are NEW (must appear in the extracted
# proof section) or a PRE-existing input (the proof must CALL it — appear in the section
# as a used identifier).
declare -a NEW=(
  "sandwichedRelRentropy_tendsto_qRelativeEnt"            # α→1⁺ continuity lemma (new)
  "sandwichedTraceFunctional_sub_one_div_eventually_le"   # Lemma E (new)
  "mix_M_eq_weighted_sum"                                 # mixture-as-Fin2-sum lemma (new)
  "ker_mix_le"                                            # kernel bookkeeping lemma (new)
  "sandwichedTraceFunctional_mix_le"                      # binary Q̃_α convexity lemma (new)
  "ofReal_prob_mix_toReal"                               # ofReal convex-combo identity lemma (new)
  "qRelativeEnt_joint_convexity"                          # the theorem (new)
)
declare -a INPUTS=(
  "sandwichedTraceFunctional_jointly_convex"   # Proposition A
  "sandwichedRelRentropy.continuousOn"         # Proposition B (called via limit lemmas)
  "ker_weighted_sum_le"                        # Lemma C
  "sandwichedTraceFunctional_pos"              # positivity
  "le_of_tendsto_of_tendsto"                   # the limit step
)
# Proof-internal case labels the paper's §7 dictionary names.
declare -a CASES=( "h_ev" "h_lhs" "h_rhs" )

pass=0; fail=0
{
  echo "Fidelity check — paper <-> Lean   ($(basename "$paper") vs $(basename "$proof"))"
  echo "Generated by fidelity-check.sh"
  echo
  printf "%-52s %-10s %-8s %-8s\n" "identifier" "kind" "in paper" "in Lean"
  printf '%.0s-' {1..82}; echo

  check() {
    local id="$1" kind="$2"
    local inpaper inlean
    grep -qF "$id" "$paper" && inpaper="yes" || inpaper="NO"
    grep -qF "$id" "$proof" && inlean="yes" || inlean="NO"
    printf "%-52s %-10s %-8s %-8s\n" "$id" "$kind" "$inpaper" "$inlean"
    if [ "$inpaper" = "yes" ] && [ "$inlean" = "yes" ]; then
      pass=$((pass+1))
    else
      fail=$((fail+1))
    fi
  }

  for id in "${NEW[@]}";    do check "$id" "new";      done
  for id in "${INPUTS[@]}"; do check "$id" "input";    done
  for id in "${CASES[@]}";  do check "$id" "case";     done

  echo
  echo "correspondences confirmed: $pass    missing: $fail"
  if [ "$fail" -eq 0 ]; then
    echo "RESULT: PASS — every load-bearing step named in the paper is present in the Lean proof."
  else
    echo "RESULT: FAIL — $fail load-bearing correspondence(s) missing (see NO above)."
  fi
} | tee "$out"

[ "$fail" -eq 0 ]
